export EDITOR="/usr/local/bin/nvim"
export DOTNET_ROOT="/usr/local/share/dotnet"
alias py="python3"
alias pip="python3 -m pip"
alias border="sh border"
alias lvim="~/.local/bin/lvim"
eval "$(starship init zsh)"
